using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Configuration;
using Facebook;
using System.IO;
using System.Text.RegularExpressions;

namespace PhotoSW.Views
    {
    public partial class Authorize : Form
        {

        private const string AppId = "1986625301590195";
        private const string AppSecret = "96495384c2721bdc583abf7f0680e2d0";
        private const string AuthUrl = "https://graph.facebook.com/oauth/authorize?client_id={0}&redirect_uri={1}&display=popup&response_type=code%20token";
        //private const string AuthUrl = "https://graph.facebook.com/oauth/authorize?client_id={0}&redirect_uri={1}&display=popup&scope=publish_stream&response_type=code%20token";
        public const string AppCallbackUrl = "https://www.facebook.com/connect/login_success.html";
        private string _authCode;
        public string AccessToken { get; set; }
        public string AuthCode
            {
            get
                {
                return _authCode;
                }
            }
        public Authorize ()
            {
            InitializeComponent();
            }
        private void Authorize_Load ( object sender, EventArgs e )
            {
            string url = string.Format(AuthUrl, AppId, AppCallbackUrl);
            webBrowser1.Navigate(url);
            webBrowser1.Refresh(WebBrowserRefreshOption.Completely);
            }

        private void webBrowser1_Navigated ( object sender, WebBrowserNavigatedEventArgs e )
            {
            // this dictionnary contain any kind of informations 'Pictures, videos, Text, it will be published through the Facebook C# SDK
            Dictionary<string, object> parameters = new Dictionary<string, object>();

            // an Image to be added to the parameters                
            FacebookMediaObject media = new FacebookMediaObject
                {
                FileName = "CodeProject",
                ContentType = "image/jpeg"
                };
            string fbImagePaht = SearchResult.selectImageForFB;
            List<string> test = SearchResult.listImageForFB;

            // byte[] img = File.ReadAllBytes(@"C:\Users\as124\Desktop\test\test2.jpg");
            // byte[] img = File.ReadAllBytes(fbImagePaht);

            //foreach(var imgtest in test)
            //    {
            //    byte[] img = File.ReadAllBytes(imgtest);
            //    media.SetValue(img);
            //    parameters.Add("source", media);
            //    }

            byte[] img = File.ReadAllBytes(fbImagePaht);
            media.SetValue(img);
            parameters.Add("source", media);

            var url = e.Url.Fragment;

            if(url.Contains("access_token") && url.Contains("#"))
                {
                this.Hide();
                url = (new Regex("#")).Replace(url, "?", 1);
                this.AccessToken = System.Web.HttpUtility.ParseQueryString(url).Get("access_token");

                var fb = new FacebookClient(this.AccessToken);

                //dynamic result = fb.Post("/me/photos", parameters);
                //var newPostId = result.id;
                List<FacebookBatchParameter> paramArry = new List<FacebookBatchParameter>();
                //string[] pic1 = new string[5];
                string pic = "pic";
                int i = 1;
                    foreach(var ImageList in test)
                    {
                    //for(var i = 1;i<2;i++)
                    //     {
                    //     pic = pic + i;
                    pic = pic + i;
                        paramArry.Add(new FacebookBatchParameter(HttpMethod.Post, "/me/photos", new Dictionary<string, object> { { "message", "picture 1 msg" }, { pic, new FacebookMediaObject { ContentType = "image/jpeg", FileName = "test.jpg" }.SetValue(File.ReadAllBytes(ImageList)) } }));
                    i++;

                      //  }
                    //paramArry.Add(new FacebookBatchParameter(HttpMethod.Post, "/me/photos", new Dictionary<string, object> { { "message", "picture 1 msg" }, { "pic1", new FacebookMediaObject { ContentType = "image/jpeg", FileName = "test.jpg" }.SetValue(File.ReadAllBytes(ImageList)) } }));

                    }

                dynamic result = fb.Batch(paramArry.ToArray());

                }

            //byte[] img = File.ReadAllBytes(fbImagePaht);
            //media.SetValue(img);
            //parameters.Add("source", media);

            //// get token from the URL generated by the Web browser, this token will be used to create a new instance of the class "FacebookClient"
            //var url = e.Url.Fragment;
            //if(url.Contains("access_token") && url.Contains("#"))
            //    {
            //    this.Hide();
            //    url = (new Regex("#")).Replace(url, "?", 1);
            //    this.AccessToken = System.Web.HttpUtility.ParseQueryString(url).Get("access_token");
            //    //Create an instance of Facebook client
            //    var fb = new FacebookClient(this.AccessToken);
            //    //post the dictionnary with the picture inside
            //    dynamic result = fb.Post("/me/photos", parameters);
            //    var newPostId = result.id;
            //    //Facebook will take some seconds to update your wall,
            //    }

            }
        }
    }
