namespace FrameworkHelper
{
    using System;

    public enum ActionType
    {
        AddBackground = 0x31,
        AddBackGround = 13,
        AddBorder = 11,
        AddCurrency = 6,
        AddDiscount = 0x65,
        ADDEditConfigData = 0x35,
        AddEditSpecPrintData = 0x38,
        AddEditSynchronizationData = 0x2f,
        AddGraphics = 0x30,
        AddPermission = 0x18,
        AddPrinter = 15,
        AddProduct = 0x1a,
        AddRole = 0x16,
        AddSubStore = 60,
        AddUser = 0x12,
        AllowPreview300 = 0x22,
        CancelOrder = 0x2b,
        CashDrawer = 0x41,
        ChangeCurrencyRate = 9,
        ChangeDefaultCurrency = 10,
        ChangeModeratePassword = 0x21,
        ChangePackage = 30,
        ChangePricing = 0x20,
        ChangePrinter = 0x10,
        ChangesinLocationAllocationtoSubstore = 0x3e,
        ChangeUserRole = 0x15,
        ClosingForm = 0x6d,
        CreatePackage = 0x1d,
        CreateRole = 0x36,
        DeleteBackground = 0x3a,
        DeleteBorder = 0x3b,
        DeleteCurrency = 7,
        DeleteDiscount = 0x66,
        DeleteGraphics = 0x39,
        DeletePackage = 0x1f,
        DeletePermission = 0x19,
        DeletePrinter = 0x11,
        DeleteProduct = 0x1b,
        DeleteRole = 0x17,
        DeleteSubStore = 0x67,
        DeleteUser = 20,
        DisablePreview300 = 0x23,
        EditaPackage = 0x40,
        EditCurrency = 8,
        EditPhoto = 4,
        EditProduct = 0x1c,
        EditSubStore = 0x3d,
        EditUser = 0x13,
        EmailFinancialReport = 0x69,
        GenerateOrder = 0x2a,
        GroupCleared = 0x43,
        Loggingtowindows = 0x2e,
        Login = 0x26,
        Logout = 0x27,
        MinimizeToWindows = 0x68,
        ModeratePhoto = 3,
        MovePrint = 0x3f,
        OpeningForm = 0x6c,
        PreviewPhoto = 1,
        PreviewPhotoHighResolution = 2,
        PrinterAdded = 0x33,
        PrinterDeleted = 0x34,
        ReceiptRePrint = 0x42,
        RefundOrder = 40,
        RemapPrinter = 0x6b,
        RemoveBackGround = 14,
        RemoveBorder = 12,
        RePrint = 0x2c,
        ResendEmail = 0x6a,
        ShutDown = 0x29,
        TemperAlert = 0x2d,
        UnlockPhoto = 5
    }
}

