using System;

namespace PhotoSW.DataLayer
{
	public enum ConfigParams
	{
		IsBarcodeActive = 1,
		DefaultMappingCode,
		ScanType,
		LostImgTimeGap,
		OnlineImageResize,
		StorageMediaImageResize,
		Online,
		DgServiceURL,
		DbBackupPath,
		CleanUpTable,
		HfBackupPath,
		ScheduleBackup,
		IsBackupScheduled,
		IsRecursive,
		IntervalCount,
		IntervalType,
		CleanUpDaysBackup,
		DigimagicBrightness,
		DigimagicContrast,
		DigimagicSharpen,
		Contrast,
		Brightness,
		IsDeleteFromUSB,
		MktImgPath,
		MktImgTimeInSec,
		FtpFolder,
		FtpIP,
		FtpPwd,
		FtpUid,
		SampleImagePath,
		DisplayDuration,
		ScreenStartTime,
		IsScreenSaverActive,
		IsDefaultBackImageEnabled,
		DefaultBackImagePath,
		IsVersionUpdateEnabled,
		UpdateServicePath,
		IsAnonymousQrCodeEnabled,
		ProductPreview,
		IsPrepaidAutoPurchaseActive,
		CleanUpDaysOldBackup,
		ResizeHeight,
		ResizeWidth,
		FrameRate,
		OutputFormat,
		VideoCodecs,
		AudioCodecs,
		IsEnabledVideoEdit,
		IsEnabledRFID,
		RFIDScanType,
		RFIDFlushInHour,
		EnablePaymentScreenOnClientView,
		Card,
		Cash,
		IsOrderwiseLoadBalancingActive,
		IsPhotographerSerailSearchActive = 67,
		IsSyncedEnabled = 69,
		SyncServiceInterval,
		SyncDataDelay,
		IsEnabledSessionSelect,
		IsEnabledSelectEnd,
		ShowAllSubstorePhotos,
		IsEnableSingleScreenPreview,
		SequencePrefix,
		BackUpEmailAddress,
		BackUpEmailSubject,
		IsEnableSlipPrint,
		ImageBarCodeTextFontSize,
		IsEnablePartialEditedImage = 182,
		SyncImageType = 194,
		RfidFlushDateTime = 81,
		IsRecursiveRfid,
		RfidRecursiveDays,
		RfidFlushReceiverEmail,
		RfidRecursiveExcludeDays,
		RfidFlushType,
		IsEnableAutoVidProcessing = 56,
		AutoVidProductId,
		VideoWriterSettings,
		ApplyMP4CUDA,
		IsRotatedVideo,
		AutoVideoLength,
		AutoVidDisplayEnabled,
		AutoVidDisplayFolder,
		AutoVidApplyChroma,
		AutoVidChromaColor,
		AutoVidChromaBackgroundID,
		NoOfDisplayScreens = 87,
		IsCyclicDisplay,
		QRCodeAutoPurchase,
		FlipVidAspectRatio,
		RFIDAssociationType,
		RFIDAssociationTimeFrame,
		ImageBarCodeColor,
		BarCodeOrientation = 147,
		BarCodePostion,
		ColorCode = 94,
		ScheduleBackupDaily,
		IsMobileRfidEnabled,
		ResizeImage,
		VisioForgeLicenseKey,
		VisioForgeUsername,
		VisioForgeEmailId,
		MediaPlayerLicenseKey,
		LiveCaptureLicenseKey,
		CudaCodec,
		DebugVisioForge,
		LogFolderPath,
		IsAutoColorCorrection,
		QRCodeLengthSetting,
		VideoProfileId,
		IsCorrectAtDownloadActive,
		IsContrastCorrection,
		IsGammaCorrection,
		IsNoiseReduction,
		IsEventEmailPackage,
		ChangeTrackingAppObjectIDs,
		IsAppMemoryOverflow,
		CalenderPrintMargin,
		ReSyncDataDelay,
		IsGreenScreenFlow = 119,
		IsAdvancedVideoEditActive,
		AutomatedVideoEditWorkFlow = 123,
		MarginValue4X6_2 = 121,
		SingleScreenPreviewAngle = 126,
		IsOpeningProcMendatory = 122,
		SiteRevenueForSellingLocation = 124,
		ClosingProcTime,
		IsEnableImageEditingMDownload = 179,
		FailedOnlineOrderCleanupDays,
		NoOfScreenPW = 127,
		DelayTimePW,
		PreviewTimePW,
		HighLightTimePW,
		IsMktImgPW,
		MktImgPathPW,
		WaterMarkPathPW,
		IsLogoPW,
		LogoPathPW,
		IsPreviewEnabledPW,
		IsSpecImgPW,
		VerticalBorderPW,
		HorizentalBorderPW,
		TripCamCleanupDays,
		ImixCleanUpDays,
		PreviewWallDummyTag,
		PreviewWallLogoPosition = 149,
		PreviewWallRFIDPostion,
		IsVisibleGumBallZeroScore = 177,
		IsVisibleGumBallZeroScoreOnImage,
		VideoFlipMode = 151,
		ValidateQRCode,
		DynamicBGFunctionalityActive = 156,
		MaxDelayAllowedInDummyCaptureDownload = 155,
		IsPrintButtonVisible = 154,
		TripCameraPropertyPassword = 157,
		GumRideAvailableLocations,
		GumRideFontSize,
		GumRideFontColor,
		GumRideFontWeight,
		GumRideBackgrondColor,
		GumRidePosition,
		GumRideMargin,
		GumRideFilePath,
		IsGumRideActive,
		IsGumPlayerScoreVisible,
		GumRideFontStyle,
		GumRideFontFamily,
		GumRideTextFileTimeOut = 173,
		QrCodeOnlineProductURL,
		QrCodeOnlineProductText,
		GumRideInputPhotoPath = 181,
		GumballScoreSeperater = 201,
		IsPrefixActiveFlow,
		PrefixPhotoName,
		PrefixScoreFileName,
		ExportPath = 143,
		ScheduledTime,
		IsServiceRecursive,
		ExportReportEmailAddress,
		IsAutoVideoFrameExtEnabled = 170,
		VideoFrameCount,
		VideoFramePositions,
		VideoFrameCropRatio = 176,
		IsResyncActive = 195,
		InitialResyncDateTime,
		ResyncIntervalCount,
		ResyncIntervalType,
		ResyncMaxRetryCount,
		SmallWalletWith4ImageCutter,
		ReceiptLogoPath = 205
	}
}
