using System;

namespace FrameworkHelper
{
	public enum ActionType
	{
		PreviewPhoto = 1,
		PreviewPhotoHighResolution,
		ModeratePhoto,
		EditPhoto,
		UnlockPhoto,
		AddCurrency,
		DeleteCurrency,
		EditCurrency,
		ChangeCurrencyRate,
		ChangeDefaultCurrency,
		AddBorder,
		RemoveBorder,
		AddBackGround,
		RemoveBackGround,
		AddPrinter,
		ChangePrinter,
		DeletePrinter,
		AddUser,
		EditUser,
		DeleteUser,
		ChangeUserRole,
		AddRole,
		DeleteRole,
		AddPermission,
		DeletePermission,
		AddProduct,
		DeleteProduct,
		EditProduct,
		CreatePackage,
		ChangePackage,
		DeletePackage,
		ChangePricing,
		ChangeModeratePassword,
		AllowPreview300,
		DisablePreview300,
		Login = 38,
		Logout,
		RefundOrder,
		ShutDown,
		GenerateOrder,
		CancelOrder,
		RePrint,
		TemperAlert,
		Loggingtowindows,
		AddEditSynchronizationData,
		AddGraphics,
		AddBackground,
		PrinterAdded = 51,
		PrinterDeleted,
		ADDEditConfigData,
		CreateRole,
		AddEditSpecPrintData = 56,
		DeleteGraphics,
		DeleteBackground,
		DeleteBorder,
		AddSubStore,
		EditSubStore,
		ChangesinLocationAllocationtoSubstore,
		MovePrint,
		EditaPackage,
		CashDrawer,
		ReceiptRePrint,
		GroupCleared,
		AddDiscount = 101,
		DeleteDiscount,
		DeleteSubStore,
		MinimizeToWindows,
		EmailFinancialReport,
		ResendEmail,
		RemapPrinter,
		OpeningForm,
		ClosingForm
	}
}
