using System;
using System.Runtime.InteropServices;

namespace BurnMedia
{
	public enum IMAPI_FORMAT2_RAW_CD_WRITE_ACTION
	{
		[TypeLibVar(64)]
		IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_UNKNOWN,
		IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_PREPARING,
		IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_WRITING,
		IMAPI_FORMAT2_RAW_CD_WRITE_ACTION_FINISHING
	}
}
