using System;

namespace BurnMedia
{
	public enum IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE
	{
		IMAPI_FORMAT2_RAW_CD_SUBCODE_PQ_ONLY = 1,
		IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_COOKED,
		IMAPI_FORMAT2_RAW_CD_SUBCODE_IS_RAW
	}
}
