using System;

namespace BurnMedia
{
	public enum IMAPI_MEDIA_PHYSICAL_TYPE
	{
		IMAPI_MEDIA_TYPE_UNKNOWN,
		IMAPI_MEDIA_TYPE_CDROM,
		IMAPI_MEDIA_TYPE_CDR,
		IMAPI_MEDIA_TYPE_CDRW,
		IMAPI_MEDIA_TYPE_DVDROM,
		IMAPI_MEDIA_TYPE_DVDRAM,
		IMAPI_MEDIA_TYPE_DVDPLUSR,
		IMAPI_MEDIA_TYPE_DVDPLUSRW,
		IMAPI_MEDIA_TYPE_DVDPLUSR_DUALLAYER,
		IMAPI_MEDIA_TYPE_DVDDASHR,
		IMAPI_MEDIA_TYPE_DVDDASHRW,
		IMAPI_MEDIA_TYPE_DVDDASHR_DUALLAYER,
		IMAPI_MEDIA_TYPE_DISK,
		IMAPI_MEDIA_TYPE_DVDPLUSRW_DUALLAYER,
		IMAPI_MEDIA_TYPE_HDDVDROM,
		IMAPI_MEDIA_TYPE_HDDVDR,
		IMAPI_MEDIA_TYPE_HDDVDRAM,
		IMAPI_MEDIA_TYPE_BDROM,
		IMAPI_MEDIA_TYPE_BDR,
		IMAPI_MEDIA_TYPE_BDRE,
		IMAPI_MEDIA_TYPE_MAX = 19
	}
}
