using System;

namespace BurnMedia
{
	public enum IMAPI_PROFILE_TYPE
	{
		IMAPI_PROFILE_TYPE_INVALID,
		IMAPI_PROFILE_TYPE_NON_REMOVABLE_DISK,
		IMAPI_PROFILE_TYPE_REMOVABLE_DISK,
		IMAPI_PROFILE_TYPE_MO_ERASABLE,
		IMAPI_PROFILE_TYPE_MO_WRITE_ONCE,
		IMAPI_PROFILE_TYPE_AS_MO,
		IMAPI_PROFILE_TYPE_CDROM = 8,
		IMAPI_PROFILE_TYPE_CD_RECORDABLE,
		IMAPI_PROFILE_TYPE_CD_REWRITABLE,
		IMAPI_PROFILE_TYPE_DVDROM = 16,
		IMAPI_PROFILE_TYPE_DVD_DASH_RECORDABLE,
		IMAPI_PROFILE_TYPE_DVD_RAM,
		IMAPI_PROFILE_TYPE_DVD_DASH_REWRITABLE,
		IMAPI_PROFILE_TYPE_DVD_DASH_RW_SEQUENTIAL,
		IMAPI_PROFILE_TYPE_DVD_DASH_R_DUAL_SEQUENTIAL,
		IMAPI_PROFILE_TYPE_DVD_DASH_R_DUAL_LAYER_JUMP,
		IMAPI_PROFILE_TYPE_DVD_PLUS_RW = 26,
		IMAPI_PROFILE_TYPE_DVD_PLUS_R,
		IMAPI_PROFILE_TYPE_DDCDROM = 32,
		IMAPI_PROFILE_TYPE_DDCD_RECORDABLE,
		IMAPI_PROFILE_TYPE_DDCD_REWRITABLE,
		IMAPI_PROFILE_TYPE_DVD_PLUS_RW_DUAL = 42,
		IMAPI_PROFILE_TYPE_DVD_PLUS_R_DUAL,
		IMAPI_PROFILE_TYPE_BD_ROM = 64,
		IMAPI_PROFILE_TYPE_BD_R_SEQUENTIAL,
		IMAPI_PROFILE_TYPE_BD_R_RANDOM_RECORDING,
		IMAPI_PROFILE_TYPE_BD_REWRITABLE,
		IMAPI_PROFILE_TYPE_HD_DVD_ROM = 80,
		IMAPI_PROFILE_TYPE_HD_DVD_RECORDABLE,
		IMAPI_PROFILE_TYPE_HD_DVD_RAM,
		IMAPI_PROFILE_TYPE_NON_STANDARD = 65535
	}
}
